#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
APP_PATH="$DOKKU_ROOT/$APP"
echo "-----> Copying any files from app's .dokku/* to ${APP_PATH}..."

CONFIG_FILES=$(docker run -i -a stdout $IMAGE /bin/bash -c "find /app/.dokku/ -type f")
CID=$(docker run -d $IMAGE /bin/sh)
for file in $CONFIG_FILES; do
	docker cp $CID:$file $APP_PATH || true
done
sleep 2 # give docker a moment to collect itself. possibly related to https://github.com/docker/docker/issues/5938
docker rm -f $CID
